// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://catkwovqwlqtstmkhqcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdGt3b3Zxd2xxdHN0bWtocWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODk3ODQsImV4cCI6MjA3MjM2NTc4NH0.8yGVAucmfN61-LIqP1WPIjboh2UrzShopybX0xh6Iq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});